version: '3.8'

services:
  beatzy:
    build: .
    container_name: beatzy
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_ID=${DISCORD_ID}
    volumes:
      - ./cookies.txt:/app/cookies.txt   # optional, for YouTube cookies
    stdin_open: true
    tty: true